version: "3.8"
services:
    nats:
        image: nats
        hostname: nats
        restart: unless-stopped
        environment:
            - TZ=${TIMEZONE}
        volumes:
            - ./conf/nats:/etc/nats
        ports:
            - "4222:4222"
            - "6222:6222"
            - "8222:8222"
        networks:
            - nats
############
# NETWORKS #
############
networks:
    nats: